server:
  port: 8010
spring:
    application:
        name: adminserver
#    cloud:
#        config:
#             server:
#                 git:
#                     uri: https://github.com/GusevAnton/config
logging:
    file: logs/AdminService.log
    level: debug